Document temp-sense-gen flow and improve docs structure
idea-fasoc/OpenFASOC pull request #100
Opened 2022-09-16 00:39 UTC by luccareinehr

The temp-sense-gen flow is documented in this file: `docs/source/flow-tempsense.rst`. It is uploaded here too: https://openfasoc-py38.readthedocs.io/en/docs-tempsense/generators.html

I also tried to take the pages that were already written in the docs and organize them more logically. So, for example, the Home page now points to the Getting Started page, which at the end points to further documentation (generator flow docs and notebook examples). Please take a look: https://openfasoc-py38.readthedocs.io/en/docs-tempsense/index.html

Finally, I moved all notebooks to the `docs/source/notebooks/` folder, as well as the `notebookFiles/` folder from #99 which gets renamed here to `aux_files/` (also changed in the nb for compatibility).

Any request or feedback is appreciated!

Closes #78

2022-09-16 13:04 UTC, saicharan0112 requested changes
@luccareinehr 
1. You might want to modify the notebooks that are present in the https://openfasoc-py38.readthedocs.io/en/docs-tempsense/examples.html page. These have been updated after your PR. The explanation looks deep, which looks good to me, for people who want to understand how the OpenFASOC generator works. 
2. These versions mentioned here https://openfasoc-py38.readthedocs.io/en/docs-tempsense/getting-started.html#manual-installation are intended to change/update after this CI (https://github.com/idea-fasoc/OpenFASOC/actions/workflows/ci.yml). Not sure how you are planning to update them.
3. You don't think we can reuse the README file somewhere for the badges and other dynamic info?

2022-09-16 13:05 UTC, saicharan0112 commented
BTW congratulations... Your PR is the 100th PR of OpenFASOC ;)

2022-09-16 15:27 UTC, luccareinehr commented
@saicharan0112 Congrats to us all on reaching PR #100! and the repo can only grow :)

On the points:
1. It's weird because that's coded in the [exemples.rst](https://github.com/idea-fasoc/OpenFASOC/pull/100/files#diff-a7edaa326e0e91de9c1d6ee49809f1a52b99e3a564d40802909fe7bc1f00c14fR9) file, I have no idea why it doesn't show up in my readthedocs. I just tested building these docs locally with `make html` and the notebook appears there

2. They're being fetched from the README (with the `.. include::` directive), so the versions should get updated automatically (unless the README structure changes drastically)

3. Yes, definitely. I'm not sure how to add it though. I thought maybe adding the README content in the docs home under "What is OpenFASoC", tell me what do you think: https://openfasoc-py38.readthedocs.io/en/docs-tempsense-2/. Is it alright or seems too crowded?

2022-09-16 15:31 UTC, luccareinehr commented
+ gotta test if the notebooks are still working, since I moved them to another folder

2022-09-18 01:41 UTC, saicharan0112 commented
@luccareinehr just change the notebooks (I think we have the updated ones). and we are good to go. I don't think we need to have two links (example and introduction). The one Ali updated  (introduction) is much better. But we can have a separate section for notebooks cuz we can eventually add other generators' notebooks to that.

2022-09-18 09:35 UTC, luccareinehr commented
@saicharan0112 Done! Looks right?

2022-09-18 10:26 UTC, saicharan0112 approved these changes
This looks very clear @luccareinehr !

2022-09-19 03:09 UTC, msaligane approved these changes

2022-09-19 03:09 UTC, merged