LDO: notebook add auto-sims, make JSON dump, arrsize bug fix, add notebook to the docs
idea-fasoc/OpenFASOC pull request #176
Opened 2023-01-30 06:18 UTC by alibillalhammoud

This PR includes several LDO updates. Changes and function information are commented thoroughly within python comments and annotations. Please let me know if you catch any bugs or if I should add any changes.

@saicharan0112 I added the LDO notebook to the docs by adding the path in the examples.rst file. Let me know if I did this correctly.

2023-02-01 01:58 UTC, saicharan0112 commented
@alibillalhammoud : Yeah that should work I guess.

2023-02-01 02:02 UTC, msaligane commented
@proppy FYI.

2023-02-01 02:55 UTC, saicharan0112 commented
@alibillalhammoud : Do you see this issue while running the verilog target in the notebook?

```
....
...
.
cd flow && make nuke
make[1]: Entering directory '/content/OpenFASOC/openfasoc/generators/ldo-gen/flow'
[INFO][FLOW] Using platform directory ../../../common/platforms/
Makefile:66: ../../../common/platforms//config.mk: No such file or directory
make[1]: *** No rule to make target '../../../common/platforms//config.mk'.  Stop.
make[1]: Leaving directory '/content/OpenFASOC/openfasoc/generators/ldo-gen/flow'
make: [Makefile:76: clean] Error 2 (ignored)
....
...
.
```

2023-02-01 04:01 UTC, lulu9312 commented
@alibillalhammoud : Can you cross check the capacitor value mentioned in notebook.

2023-02-01 06:24 UTC, alibillalhammoud commented
@saicharan0112 This is not an issue. This is caused by make clean target (will try to clean config.mk, but if it is not there will show this message).

@lulu9312 I fixed this now in the notebook.

2023-02-02 17:52 UTC, alibillalhammoud commented
@lulu9312 The notebook vref connection fix also resolved the issue we had with the plots. I am using regex to find the VREF node so the new code works with new (recent) and old (~8.3.315) versions of magic.

2023-02-03 02:59 UTC, lulu9312 commented
@alibillalhammoud That's Great! I saw you fixed the sim header issue. I had fixed that issue on my side while running sims.Once this PR is merged will run full flow to catch bugs/issues if any.

2023-02-03 05:13 UTC, alibillalhammoud commented
@saicharan0112 I would like to include the notebook simulation outputs in the github file so that when user's open the notebook, they do not need to run everything to see example output. This is causing the pre-commit to fail. The pre-commit run removes all the outputs from the notebook. Any ideas on how to resolve this?

2023-02-04 04:50 UTC, msaligane commented
@alibillalhammoud pre-commit is failing.

2023-02-04 05:28 UTC, saicharan0112 commented
> 

I am not sure about that. What are those results btw? Images, tables?

2023-02-04 05:29 UTC, saicharan0112 commented
> @saicharan0112 I would like to include the notebook simulation outputs in the github file so that when user's open the notebook, they do not need to run everything to see example output. This is causing the pre-commit to fail. The pre-commit run removes all the outputs from the notebook. Any ideas on how to resolve this?

I am not sure about that. What are those results btw? Images, tables?

2023-02-09 02:14 UTC, saicharan0112 requested changes
Can you add this line in the .pre-commit-config.yml file before `repos` start (before line 1)?
```
default_language_version:
    python: python3.7
    python: python3
```

2023-02-10 04:03 UTC, alibillalhammoud commented
@msaligane Sai and I met to debug the pre-commit issues. We saw weird behavior so commented out the pre-commit auto run on push temporarily. @saicharan0112 can provide more about this.

2023-02-10 04:34 UTC, saicharan0112 commented
@msaligane you should still be able to run it manually. The workflow is still on the list. I think we are just dedicating extra time on fixing this non-functional thing. Since we are already running the smoke test on the generators, I think its fine to ignore this pre-commit check.

2023-02-10 20:30 UTC, msaligane approved these changes

2023-02-10 20:30 UTC, merged