DLDO: Update in make target, parallel sim runs
idea-fasoc/OpenFASOC pull request #190
Opened 2023-03-17 11:59 UTC by lulu9312

This PR includes:
1. Simulations now run in parallel by the use of sp.Popen.
2. Updated the make target to generate spice netlist.
3. Seperated the post processing functions to seperate python file.

2023-03-26 06:33 UTC, saicharan0112 requested changes
Are simulations running only for postPEX netlists? Do we have an option to choose between/both prePEX and postPEX simulations ?

2023-03-26 10:52 UTC, lulu9312 commented
@saicharan0112 Yes, by default the simulations run for postPEX netlists. Passing prePEX_sim_dir and pex=false to function prepare_scripts() runs prePEX simulations.

2023-03-26 14:03 UTC, saicharan0112 commented
Shouldn't this be an option along with the current and voltage options to the make target... like the temp-sense generator?

2023-03-26 14:36 UTC, lulu9312 commented
Yes correct. I will update the make target to add option for prePEX/postPEX sim.

2023-03-29 01:01 UTC, msaligane commented
@lulu9312 and @saicharan0112 - As discussed I would like to have the spice tb as regression tests. We also need to find ways to test the Verilog generation, DRC and LVS results/

2023-03-29 08:46 UTC, saicharan0112 commented
Yeah, I am working on the simulation regression part. I am thinking of
having a fixed testcase and compare results with that.

On Wed, 29 Mar, 2023, 6:32 am Mehdi Saligane, ***@***.***>
wrote:

> @lulu9312 <https://github.com/lulu9312> and @saicharan0112
> <https://github.com/saicharan0112> - As discussed I would like to have
> the spice tb as regression tests. We also need to find ways to test the
> Verilog generation, DRC and LVS results/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/idea-fasoc/OpenFASOC/pull/190#issuecomment-1487798017>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYCOBKJ5OQOSVCDXRBWDAW3W6OCYXANCNFSM6AAAAAAV6OAH44>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-03 15:22 UTC, msaligane approved these changes

2023-04-03 15:22 UTC, merged