Add Glayout checks in CI
idea-fasoc/OpenFASOC pull request #300
Opened 2024-04-13 19:58 UTC by chetanyagoyal

This PR aims to enable CI checking for glayout. The vision is to enable DRC and LVS checks for the primitives and the components marked with the `@cell` decorator in `glayout/components`. This envolves the following changes:

- [x] Create DRC script for glayout
- [x] Create wrapper script to test all components for DRC errors
- [x] Create `.yml` file for GitHub actions
- [ ] Create LVS script (specifically for glayout)
- [ ] Create wrapper script to test all components for LVS errors

2024-04-14 06:31 UTC, chetanyagoyal commented
@alibillalhammoud @andylithia can you help out with a review?

2024-04-21 18:43 UTC, chetanyagoyal commented
@msaligane all checks have been added, but this shouldn't be merged until gf180 is added to docker image (required for gf180 drc run)

2024-05-09 14:43 UTC, alibillalhammoud requested changes
See reviews

2024-05-09 14:43 UTC, alibillalhammoud commented on .github/scripts/run_glayout_lvs.py
> +    for i, pattern in enumerate(patterns):
do list comprehension here

2024-05-09 14:43 UTC, alibillalhammoud commented on openfasoc/common/drc-lvs-check/run_lvspex.sh
> +  load diff_test_flat
Make the first thing LDO, may break the generators

2024-05-09 14:43 UTC, alibillalhammoud commented on openfasoc/common/drc-lvs-check/custom_block_tool/block_lvs_check_sky130pdk/Makefile
> +CDL_FILE_PATH = /home/chetanya/OpenFASOC/openfasoc/common/platforms/sky130hd/cdl/sky130_fd_sc_hd.spice
dont hardcode paths

2024-05-09 14:43 UTC, alibillalhammoud commented on docs/source/notebooks/glayout/glayout_opamp.ipynb
> +      "version": "3.8.10"
revert this

2024-05-09 14:44 UTC, alibillalhammoud commented on docs/source/notebooks/glayout/glayout_opamp.ipynb
> +      "version": "3.8.10"
current notebook is known to work

2024-05-18 16:31 UTC, chetanyagoyal commented
this should not be merged yet, many changes need to be made

2024-05-23 12:52 UTC, closed without merging