Glayout DRC and LVS in CI
idea-fasoc/OpenFASOC pull request #304
Opened 2024-05-28 17:27 UTC by chetanyagoyal

Implements the following changes - 

1. Create a pythonic parser file that: 
- Writes the specified component's gds
- Writes its netlist
- Validates the DRC results by looking at the number of lines in the reports and the magic subprocess return codes
- Validates the LVs results by parsing the report for exceptions and checks the magic (extraction) and netgen (LVS) subprocess return codes
2. Create a `yaml` workflow file to: 
- pull the stable docker image
- run the parser file by specifying the component to run drc and lvs for
3. makes the antenna diodes optional in diff_pair_ibias_netlist to allow for NoneType being passed (when `with_antenna_diodes=0` in opamp)
4. updates the `diff_pair_ibias` code to account for antenna diodes being passed as 0
5. Update the differential to single ended converter netlist 
- `.subckt` definition now matches the parameters being passed
- this makes things the `DIFF_TO_SIGLE` netlist LVS clean
6. allow the user to omit the output stage in the opamp
- done to make the opamp lvs clean
- all errors (other than in diff pair netlist and nmos netlist were solved by this)
7. Switch around pin around in mimcap netlist reference in opamp gain stage
8. Update the current mirror netlist:
- to use length as minimum transistor length if passed as None
- pass length and width to the `.subckt` statements 
9. General quality of life improvements in lvs, drc (magic and klayout) in `mappedpdk`
10. modify fet netlist:
- to pass length, width, multipliers and fingers to `.subckt` calls
  - length is ltop
  - width is mtop
  - fingers * multipliers is mtop (the number of parallel devices)
  - multipliers is dummy multipliers
- divide the number of main fet multipliers by two to fix the reported width from cdl always being double of whats in the extracted spice
10. add `with_pins` argument in `generate_netlist` to allow removal of top level's pins

2024-05-30 03:59 UTC, msaligane commented
is this ready for review?

2024-05-30 04:54 UTC, d-m-bailey commented
@msaligane the `mappedpdk.py` file contains the following extraction commands
```
select top cell
extract all
ext2spice lvs
ext2spice -o {str(lvsmag_path)}

load {design_name}
extract all
ext2spice lvs 
ext2spice rthresh 0
ext2spice cthresh 0
ext2spice -o {str(pex_path)}

load {design_name}
extract all
ext2spice cthresh 0
ext2spice -o {str(sim_path)}
```
I think the same extraction is happening 3 times. I don't think the ext2spice modify the extracted data (`*.ext` files), just how that information is netlisted.

The default extract option is to connect virtual nets (nets with the same name) that are not physically connected.

You might want to use the [detailed parasitic resistance flow described here](http://opencircuitdesign.com/magic/commandref/extresist.html).

The netgen lvs command used is a one line command that should work for simple circuits. Multiple netlists and mixed signal designs require extra handling.

You might want to add a check for unexpected blackboxes. netgen will sometimes match an empty subckt to an actual layout or visa versa because it assumes that one or the other is a blackbox.

2024-05-30 11:52 UTC, chetanyagoyal commented
> Contributor

@d-m-bailey I addressed the repeated `.ext` extractions in [this commit](https://github.com/idea-fasoc/OpenFASOC/pull/304/commits/a701be0198b1cd06bea2be3b8309771590140dad). 

- Adding `ext2resist` didn't seem to make a difference in the report. 
- From what I read in the documentation, adding `-blackbox` seemed like a good check to add

Thank you for the help!

2024-06-03 16:55 UTC, chetanyagoyal commented
@msaligane this is ready to merge

2024-06-03 17:25 UTC, alibillalhammoud commented
@srpathen @arldai can you take a look?

2024-06-04 04:32 UTC, alibillalhammoud requested changes
Major changes are fine, I think we should hold off on merging this PR until the other PRs are merged.

2024-06-04 04:32 UTC, alibillalhammoud commented on .github/scripts/expected_sim_outputs/opamp/means.json
remove or explain why this is here

2024-06-04 04:32 UTC, alibillalhammoud commented on .github/scripts/expected_sim_outputs/opamp/variances.json
remove or explain why this is here

2024-06-04 04:32 UTC, alibillalhammoud commented on .github/scripts/test_glayout.py
The test PR should be merged before this PR, so I will ignore this file for now

2024-06-04 13:16 UTC, chetanyagoyal commented on .github/scripts/expected_sim_outputs/opamp/means.json
this is used for the opamp spice testbench simulations as a lookup for means/variances of the 100 runs i did

2024-06-04 13:16 UTC, chetanyagoyal commented on .github/scripts/expected_sim_outputs/opamp/variances.json
same here

2024-06-05 20:49 UTC, closed without merging