general fixes
idea-fasoc/OpenFASOC pull request #317
Opened 2024-06-07 13:53 UTC by chetanyagoyal

2024-06-07 17:15 UTC, alibillalhammoud requested changes
make changes as described, otherwise LGTM

2024-06-07 17:15 UTC, alibillalhammoud commented on openfasoc/generators/glayout/glayout/flow/pdk/mappedpdk.py
remove git keeps

2024-06-07 17:15 UTC, alibillalhammoud commented on openfasoc/generators/glayout/glayout/syntaxer/relational.py
Do you want me to add my changes for this, I can commit them to your fork

2024-06-07 18:23 UTC, chetanyagoyal commented on openfasoc/generators/glayout/glayout/syntaxer/relational.py
yes sounds good

2024-06-08 13:06 UTC, msaligane approved these changes

2024-06-08 13:06 UTC, merged