Adding code that trains on different LLM models and added the introduction to GLayout notebook
idea-fasoc/OpenFASOC pull request #323
Opened 2024-06-19 22:51 UTC by srpathen

1. We train on phi, mistral, and codestral
2. Added introduction to GLayout notebook that introduces many of the functions that the participants will use

2024-06-20 14:56 UTC, msaligane approved these changes

2024-06-20 14:57 UTC, msaligane commented
The CI is failing for these. Is this normal? @chetanyagoyal and @srpathen

2024-06-20 16:48 UTC, chetanyagoyal commented
The CI failing is unintended behaviour, we will look into this

2024-06-27 13:30 UTC, chetanyagoyal requested changes

2024-06-27 13:30 UTC, chetanyagoyal commented on .github/workflows/glayout_opamp_sim.yml
> +                      python3 -m pip install numpy==1.23.3 &&\
can this be implemented in the requirements.txt file instead, pin the version there

2024-06-27 13:30 UTC, chetanyagoyal commented on .github/workflows/glayout_sky130.yml
> +                    python3 -m pip install numpy==1.23.3 &&\
same here

2024-06-27 13:30 UTC, chetanyagoyal commented on .github/workflows/glayout_sky130.yml
> +                    python3 -m pip install numpy==1.23.3 &&\
same here

2024-06-27 13:30 UTC, chetanyagoyal commented on .github/workflows/glayout_sky130.yml
> +                    python3 -m pip install numpy==1.23.3 &&\
same here

2024-06-27 13:31 UTC, chetanyagoyal commented
Glayout changes are okay, they are previously unmerged changes to `llm`

2024-06-28 11:22 UTC, chetanyagoyal commented
@srpathen scipy conflicts with the numpy version you're installing, we need numpy==1.23.5 or greater

2024-06-28 16:01 UTC, srpathen commented
Updated the numpy version to 1.23.5

2024-06-30 01:50 UTC, msaligane commented
Is this ready for a second review?

2024-07-02 12:56 UTC, chetanyagoyal commented
@msaligane this can be merged

2024-07-05 18:33 UTC, msaligane approved these changes

2024-07-05 18:33 UTC, merged