Update dependencies.sh
idea-fasoc/OpenFASOC pull request #324
Opened 2024-06-23 12:24 UTC by baharmoosavi

2024-06-23 12:27 UTC, baharmoosavi reviewed
I can't access https://git.code.sf.net/p/ngspice/ngspice , but it is possible with git:// ...

2024-06-24 09:45 UTC, chetanyagoyal commented
can you enable workflows on your repo to check if they pass @baharmoosavi

2024-06-24 09:47 UTC, chetanyagoyal requested changes

2024-06-24 09:47 UTC, chetanyagoyal commented on dependencies.sh
> + git clone git://git.code.sf.net/p/ngspice/ngspice
can you make a similar change in the Dockerfile to see if it passes in the CI

2024-07-02 12:57 UTC, chetanyagoyal commented
closing this soon as it seems like a non-issue. @baharmoosavi are you planning to work on this further?

2024-07-15 17:29 UTC, closed without merging