RL refactor
idea-fasoc/OpenFASOC pull request #333
Opened 2024-08-13 05:01 UTC by alibillalhammoud

2024-08-13 05:10 UTC, chetanyagoyal reviewed
Remove the test1.py. 
Otherwise LGTM!

2024-08-13 05:10 UTC, chetanyagoyal commented on openfasoc/MLoptimization/test1.py
Remove this file?

2024-08-20 00:22 UTC, msaligane commented
Is this ready for review?

2024-08-21 21:07 UTC, msaligane commented
@alibillalhammoud

2024-08-21 23:45 UTC, alibillalhammoud commented
@msaligane not yet. I am currently rerunning on a fresh machine to verify all package versions I have listed in the requirements file are correct. Should be ready by Monday.

2024-08-25 20:10 UTC, alibillalhammoud commented
Ok all good now. This PR is ready to merge

2024-08-30 03:19 UTC, chetanyagoyal requested changes

2024-08-30 03:19 UTC, chetanyagoyal commented on openfasoc/MLoptimization/test1.py
Can you remove or refactor this file formally?

2024-08-30 03:20 UTC, chetanyagoyal commented
Otherwise lgtm!

2024-08-30 03:35 UTC, chetanyagoyal commented
@msaligane this can be merged.

2024-08-30 11:02 UTC, chetanyagoyal approved these changes

2024-09-18 21:17 UTC, closed without merging