refactor folder structure in blocks directory
idea-fasoc/OpenFASOC pull request #334
Opened 2024-08-22 18:31 UTC by chetanyagoyal

The new `blocks` folder looks like - 
- blocks 
  - elementary
    - diff_pair
      - ..
    - current_mirror
      - ..
  - composite
    - opamp
      - ..
    - ..

2024-08-22 18:35 UTC, chetanyagoyal commented
@msaligane this can be merged

2024-08-30 03:38 UTC, alibillalhammoud requested changes
You correctly updated all dependencies and paths in the syntaxer folder. strict syntax -> python conversion still works. Let us hold off on merging until #333  is merged

2024-08-30 11:22 UTC, harshkhandeparkar reviewed
Looks good to me.

2024-08-30 14:11 UTC, msaligane approved these changes

2024-08-30 14:11 UTC, merged