update MLopt
idea-fasoc/OpenFASOC pull request #346
Opened 2024-10-22 21:17 UTC by chetanyagoyal

- add utility function to test script to convert a list of opamp parameter into a list of indices into these range arrays
- fix imports in sky130_nist_tapeout.py

2024-10-23 05:36 UTC, alibillalhammoud requested changes
discard changes on the bash script

2024-10-23 05:36 UTC, alibillalhammoud commented on openfasoc/generators/glayout/tapeout/tapeout_and_RL/sky130_nist_tapeout.py
> +try:
nice, robust :+1:

2024-10-23 05:36 UTC, alibillalhammoud commented on openfasoc/MLoptimization/quickstart.bash
this does not need to change (just discard changes on this file)

2024-10-23 05:45 UTC, chetanyagoyal commented
@alibillalhammoud thanks for the review, addressed all changes

2024-10-23 05:46 UTC, chetanyagoyal commented
@msaligane this is ready to merge

2024-10-24 04:12 UTC, alibillalhammoud approved these changes

2024-10-31 14:51 UTC, msaligane approved these changes

2024-10-31 14:52 UTC, merged