C route and other fixes
idea-fasoc/OpenFASOC pull request #358
Opened 2024-12-19 11:43 UTC by Subhampal9

1. added code to add more vias at intermediate nodes of c_route
2.  minor fix in four transistor interdigitized block

2025-01-16 19:09 UTC, harshkhandeparkar commented on openfasoc/generators/glayout/glayout/flow/blocks/elementary/FVF/README.md
Can you remove these files and only keep the files relevant to the fix?

2025-01-16 19:09 UTC, harshkhandeparkar commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
Can you highlight which lines were changed? Or revert the styling changes so that the diff only shows the relevant changes.

2025-01-18 02:38 UTC, Subhampal9 commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
I have added some comments where the changes are

2025-01-24 07:49 UTC, Subhampal9 commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
> +    cwidth = cwidth if cwidth else max(width1,width2)
it is the width of the intermediate connection route

2025-01-24 07:49 UTC, Subhampal9 commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
> +    #condition checking for multiple vias at first intermediate node
okay

2025-01-24 07:54 UTC, Subhampal9 commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
> +    viastack2_dims = evaluate_bbox(viastack2,True)
via_array is taking different sizes in each case, I am not sure how I can loop it.

2025-02-01 03:32 UTC, harshkhandeparkar commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
> +    viastack2_dims = evaluate_bbox(viastack2,True)
You can create a list and iterate over it. It is not required though.

2025-02-01 03:36 UTC, Subhampal9 commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
> +    viastack2_dims = evaluate_bbox(viastack2,True)
So, should I leave it as it is?

2025-02-03 15:52 UTC, msaligane commented on openfasoc/generators/glayout/glayout/flow/routing/c_route.py
> +    viastack2_dims = evaluate_bbox(viastack2,True)
Can you create a list?

2025-02-03 15:53 UTC, msaligane requested changes
@Subhampal9 Great work! It would be good to start documenting some of the changes. Can  you add some simple readmes for c_route for instance.

2025-02-04 13:45 UTC, Subhampal9 commented
> @Subhampal9 Great work! It would be good to start documenting some of the changes. Can you add some simple readmes for c_route for instance.

Will do that soon.

2025-04-10 17:15 UTC, msaligane commented
Merged in a newer PR.

2025-04-10 17:15 UTC, closed without merging