Post-pex simulations, organized simulation options, new notebook
idea-fasoc/OpenFASOC pull request #99
Opened 2022-09-15 05:47 UTC by alibillalhammoud

This update adds the post PEX simulations and brings simulations together in a more organized fashion
I also added the developed notebook.

credits to:
@Sai provided some starter commands and helped me with edits to get the python env working correctly
@Lucca pointed me to the commands needed to get a gds dump from the database files from openroad
@Qirui provided silicon data

several updates:
simulations
	rewrite update netlist so that the "partial" simulation functionality is included for both prePEX and postPEX netlists
	add match function to find common names that should be removed from partial netlist
	substitute a standard toplvl definition
	specify optional prePEX vs postPEX simulations or both from the command line when calling the generator 
		also edit makefile to include the new command line options

notebook
	in docs/source the tempsense notebook is now further developed
	The notebook explains the temperature sensor and flow aimed at a non-expert user
	includes interactive components to visualize the flow progress and see simulation results
	stil does not include simulations (will update later today)
	uses klayout deb package

other
	Qirui's PR provided silicon data; move this into temp sense gen directory and adapt into "modelfile" (keep the A-hd data)
	add prePEX model file and add postPEX model file
	each simulation run type gets its own directory and output

2022-09-15 05:53 UTC, alibillalhammoud commented
I will run pre-commit later today.
Also please suggest notebook improvements to what I have done so far, or suggest corrections if anything appears incorrect. 
To clarify every notebook command on this PR should run to completion, so if a command fails, let me know. The notebook runs the entire flow and prints step by step graphical outputs.

2022-09-15 14:38 UTC, msaligane commented on docs/source/notebookFiles/def2gds.py
> +import copy
These files are already in the sensor's directory. Why don't you point to them?
Same for the gds files above.

2022-09-15 14:39 UTC, msaligane commented on docs/source/notebookFiles/fill.json
> +{
same as above

2022-09-15 17:09 UTC, saicharan0112 requested changes
Rename the notebook in the last line of /docs/source/index.rst to this new notebook.
OpenFASoC_temp_sense_gen -> temp_sense_genCollab

2022-09-15 17:09 UTC, saicharan0112 commented on docs/source/temp_sense_genCollab.ipynb
> +    },{"cell_type":"markdown","source":["#OpenFASoC Temperature Sensor Generator\n","Welcome!\n","This notebook serves as an introduction to the temperature sensor generator: an open-source silicon g
1. Add a separate cell in the beginning of the notebook as a header for the sphinx to include it in docs (Don't edit here, you might miss the syntax. Edit with the notebook running in the browser.) Something like below - 
![image](https://user-images.githubusercontent.com/100982953/190466536-21629f11-e395-404d-b7d8-3dfc54e51ced.png)
2. Also run all the cells and add that copy of notebook to the docs. Seeing the result of each cell will be really good in the docs.

2022-09-15 19:27 UTC, saicharan0112 commented
@alibillalhammoud let me know once you are done with the changes regarding the notebook

2022-09-15 21:31 UTC, luccareinehr commented
@alibillalhammoud looks good! Could you squash some of the commits to ease the history?

2022-09-15 21:36 UTC, merged

2022-09-15 21:36 UTC, luccareinehr approved these changes
If CI succeeds, looks good

2022-09-16 00:17 UTC, luccareinehr commented
@alibillalhammoud I see most of the files from `docs/source/notebookFiles/` look like copies of files present in other directories in openfasoc. Would it be possible to delete this folder altogether and just fetch the original files in your notebook code?

This way we can avoid breaking the notebook if the flow gets updated, and also reduce the size of the repo (that is already quite large).

2022-09-16 02:22 UTC, saicharan0112 commented
@alibillalhammoud You missed two more changes I suggested. This removed the notebook from the docs. Also the cells are not executed.
@msaligane are you not planning to display the notebook at openfasoc.readthedocs.io?

2022-09-16 02:25 UTC, msaligane commented
Yes, I missed that. We need the colab ready tonight. We can add fixes to those.
@saicharan0112 can you take care of that @alibillalhammoud is busy the next 2 days and I am working on the formatting of the colab.

2022-09-16 02:29 UTC, saicharan0112 commented
Sure. I will add that in lucca's PR.